#ifndef DYNAMICS_MODULES_H
#define DYNAMICS_MODULES_H
#include "data_structs.h"
MATRIX calc_Tbr(MATRIX, MATRIX, MATRIX);
VECTOR calc_wbi(VECTOR,VECTOR,VECTOR,MATRIX);
QUATERNION qb2i(QUATERNION,QUATERNION,double);
QUATERNION rk4_qdot(double,QUATERNION,VECTOR);
VECTOR funcEval_dwdt(MATRIX,MATRIX,VECTOR,VECTOR,VECTOR);
VECTOR rk4_wbi(MATRIX,MATRIX,VECTOR,VECTOR,VECTOR,double);
QUATERNION qr2i(QUATERNION,QUATERNION,double);
QUATERNION rk4_qri(double,QUATERNION,VECTOR);
#endif // DYNAMICS_MODULES_H
